image: nixos/unstable
packages:
  - just
  - nix
  - coreutils
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - setup: |
      nix --version
      just --version
  - check: |
      just check
      just check-outputs
  - mirror-to-github: |
      cd ~/"${SH_REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${GH_REPO}"
